const mongoose = require('mongoose')

/*
    Schmema for Summary Objects

*/

const summarySchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
    },
    summary: {
        type: String,
        required: true,
    },
    options: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Options',
    },
    dateCreated: {
        type: Date,
        required: true,
        default: Date.now,
    },
    user: {    // this is really the users id
        type: String,
        ref: 'User',
    },
    // _id: { // if we allow this field to be autogenerated, it won't be a string and querying could be difficult
    //     type: String,
    //     default: new mongoose.mongo.ObjectId().toString()
    // },
})

// define how it is serialized
// toJSON takes an obtions object which takes a transform method if we want to pass on
// transform method is called on toJSON's output before it is returned
// summarySchema.set('toJSON', {
//     transform: (originalObject, returnedObject) => {
//         returnedObject.user = returnedObject.user._id
//     }
// })

let summaryModel = mongoose.model('Summary', summarySchema)

module.exports = summaryModel